####################################################################################
#                                                                                  #
#  Copyright (c) 2014, 2015 - 2016 Axel Menzel <info@rttr.org>                     #
#                                                                                  #
#  This file is part of RTTR (Run Time Type Reflection)                            #
#  License: MIT License                                                            #
#                                                                                  #
#  Permission is hereby granted, free of charge, to any person obtaining           #
#  a copy of this software and associated documentation files (the "Software"),    #
#  to deal in the Software without restriction, including without limitation       #
#  the rights to use, copy, modify, merge, publish, distribute, sublicense,        #
#  and/or sell copies of the Software, and to permit persons to whom the           #
#  Software is furnished to do so, subject to the following conditions:            #
#                                                                                  #
#  The above copyright notice and this permission notice shall be included in      #
#  all copies or substantial portions of the Software.                             #
#                                                                                  #
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR      #
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,        #
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE     #
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER          #
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,   #
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE   #
#  SOFTWARE.                                                                       #
#                                                                                  #
####################################################################################

language: cpp
sudo: false

env:
  global:
    - ARCH_FLAGS_x86='-m32'
    - ARCH_FLAGS_x86_64=''
    - BUILD_DOCU=false

matrix:
  include:
    - os: osx
      osx_image: xcode7
      compiler: clang
      env: COMPILER=clang++ ARCH=x86_64 CHECK_FORMATTING=true UNIT_TESTS=false

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8-multilib', 'linux-libc-dev:i386']
      env: COMPILER=g++-4.8 ARCH=x86 CONF=Release UNIT_TESTS=true

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8-multilib']
      env: COMPILER=g++-4.8 ARCH=x86_64 CONF=Release UNIT_TESTS=true

    # this config fails at the moment because of disabled APT on llvm
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env: COMPILER=clang++-3.7 ARCH=x86_64 CONF=Release UNIT_TESTS=true
    # end not workint clang config
    
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8-multilib', 'linux-libc-dev:i386']
      env: LLVM_VERSION=3.7.1 ARCH=x86 CONF=Release UNIT_TESTS=true

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8-multilib']
      env: LLVM_VERSION=3.7.1 ARCH=x86_64 CONF=Release UNIT_TESTS=true
      
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8-multilib', 'linux-libc-dev:i386']
      env: LLVM_VERSION=3.8.0 ARCH=x86 CONF=Release UNIT_TESTS=true

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8-multilib']
      env: LLVM_VERSION=3.8.0 ARCH=x86_64 CONF=Release UNIT_TESTS=true

    - os: osx
      osx_image: xcode7
      compiler: clang
      env: COMPILER=clang++ ARCH=x86 CONF=Release UNIT_TESTS=true
      
    - os: osx
      osx_image: xcode7
      compiler: clang
      env: COMPILER=clang++ ARCH=x86_64 CONF=Release UNIT_TESTS=true
      
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8-multilib', 'linux-libc-dev:i386', 'libc6-dbg:i386', 'valgrind']
      env: COMPILER=g++-4.8 ARCH=x86 CONF=Debug VALGRIND=true UNIT_TESTS=true
  allow_failures:
    - env: COMPILER=clang++-3.7 ARCH=x86_64 CONF=Release UNIT_TESTS=true

before_install:
  - export CIT_ROOT=`pwd`
  - cd $CIT_ROOT

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/3rd_party"
  - cd ${DEPS_DIR}
  #######################################################################################
  # Setup default versions
  #######################################################################################
  - if [[ "${LLVM_VERSION}" == "default" ]]; then LLVM_VERSION=3.7.0; fi
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - if [[ "${COMPILER}" == "g++-4.8" ]]; then export CC=gcc-4.8; fi
  - if [[ "${ARCH}" == "x86" ]]; then export CMAKE_ARCH_FLAGS=-m32; fi
  #######################################################################################
  # Install recent CMake
  #######################################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi
  #######################################################################################
  # Install vera++
  #######################################################################################
  - if [[ "${CHECK_FORMATTING}" == "true" ]]; then brew install vera++; fi

  #######################################################################################
  # Install Clang
  #######################################################################################
  - |
    if [[ "${LLVM_VERSION}" != "" ]]; then
      CLANG_URL="http://llvm.org/releases/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz"
      mkdir clang && travis_retry wget --quiet -O - ${CLANG_URL} | tar --strip-components=1 -xJ -C clang
      export PATH=${DEPS_DIR}/clang/bin:${PATH}
      ls ${DEPS_DIR}/clang/bin
      export CXX=${DEPS_DIR}/clang/bin/clang++
      export CC=${DEPS_DIR}/clang/bin/clang
    fi

  #######################################################################################
  # Install libc++ and libc++abi (on Linux only; Xcode uses libc++ by default)
  #######################################################################################
  - |
    if [[ "${LLVM_VERSION}" != "" && "${STDLIB}" != "libstdc++" ]]; then
      if [[ "${LLVM_VERSION}" != "trunk" ]]; then
        LLVM_URL="http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}.src.tar.xz"
        LIBCXX_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxx-${LLVM_VERSION}.src.tar.xz"
        LIBCXXABI_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxxabi-${LLVM_VERSION}.src.tar.xz"
        TAR_FLAGS="-xJ"
      else
        LLVM_URL="https://github.com/llvm-mirror/llvm/archive/master.tar.gz"
        LIBCXX_URL="https://github.com/llvm-mirror/libcxx/archive/master.tar.gz"
        LIBCXXABI_URL="https://github.com/llvm-mirror/libcxxabi/archive/master.tar.gz"
        TAR_FLAGS="-xz"
      fi
      mkdir -p llvm llvm/build llvm/projects/libcxx llvm/projects/libcxxabi
      travis_retry wget --quiet -O - ${LLVM_URL} | tar --strip-components=1 ${TAR_FLAGS} -C llvm
      travis_retry wget --quiet -O - ${LIBCXX_URL} | tar --strip-components=1 ${TAR_FLAGS} -C llvm/projects/libcxx
      travis_retry wget --quiet -O - ${LIBCXXABI_URL} | tar --strip-components=1 ${TAR_FLAGS} -C llvm/projects/libcxxabi
      # clang-3.8.0 does not compile libc++.so.1.0 as 32 bit binary, the flag is for unknown reason not forwarded
      # this will fix it
      export CXX="${DEPS_DIR}/clang/bin/clang++ $CMAKE_ARCH_FLAGS"
      (cd llvm/build && cmake .. -DCMAKE_INSTALL_PREFIX=${DEPS_DIR}/llvm/install -DCMAKE_CXX_FLAGS="$CMAKE_ARCH_FLAGS")
      (cd llvm/build/projects/libcxx && make install -j2)
      (cd llvm/build/projects/libcxxabi && make install -j2)
      export CXXFLAGS="-isystem ${DEPS_DIR}/llvm/install/include/c++/v1"
      export LDFLAGS="-L ${DEPS_DIR}/llvm/install/lib -l c++ -l c++abi"
      export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/llvm/install/lib"
    fi
    
before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - if [[ "${LLVM_VERSION}" != "" ]]; then export CMAKE_ADDITIONAL_FLAGS=-stdlib=libc++; fi
  - >
      eval "ARCH_FLAGS=\${ARCH_FLAGS_${ARCH}}" ;
      (cd build && cmake
      -DCMAKE_CXX_COMPILER=${COMPILER}
      -DCMAKE_C_COMPILER=${CC}
      -DCMAKE_BUILD_TYPE=${CONF}
      -DCMAKE_CXX_FLAGS="$ARCH_FLAGS $CMAKE_ADDITIONAL_FLAGS $GCOV_FLAGS"
      -DCMAKE_C_FLAGS="$ARCH_FLAGS"
      ..)

script:
  - |
    if [[ "${CHECK_FORMATTING}" == "true" ]]; then
      # F001: Source files should not use the '\r' (CR) character
      # L001: No trailing whitespace at the end of lines
      # L002: Don't use tab characters
      # T001: One-line comments should not have forced continuation
      # T002: Reserved names should not be used for preprocessor macros
      # T009: Comma should not be preceded by whitespace, but should be followed by one
      # T013: Source files should contain the copyright notice
      find src -name \*\.h -print -o -name \*\.cpp -print | vera++ --rule F001 --rule L001 --rule L002 --rule T001 --rule T002 --rule T009 --rule T013 --error
    fi
  - |
    if [[ "${VALGRIND}" == "true" ]]; then
      # Run unit tests on two cores
      (valgrind --leak-check=full --error-exitcode=1 ${TRAVIS_BUILD_DIR}/build/bin/json_serialization)
    fi

notifications:
  email:
    - info@rttr.org
